package br.com.totvs.cia.infra.exception;

public enum StatusCodeEnum {

	BUSINESS_EXCEPTION, SECURITY_EXCEPTION, DATABASE_EXCEPTION, INTEGRATION_EXCEPTION, JOB_EXCEPTION, PARSER_EXCEPTION, EXCEPTION;
}
